version: '3.8'

services:

  elasticsearch:
    image: elasticsearch:7.17.18
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elk_data:/usr/share/elasticsearch/data/
      - ./elk-config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
    networks:
      - elk

  logstash:
    image: logstash:7.17.18
    container_name: logstash
    ports:
      - 5044:5044
      # - "9600:9600"
    volumes:
      - ./elk-config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk-config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ls_data:/usr/share/logstash/data
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.17.18
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ./elk-config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - kb_data:/usr/share/kibana/data
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    image: elastic/filebeat:7.17.18
    container_name: filebeat
    user: root
    command: ["filebeat", "-e", "--strict.perms=false"]
    volumes:
      - ./elk-config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/syslog:/var/log/syslog
      - /var/log/auth.log:/var/log/auth.log
    networks:
      - elk
    depends_on:
      - elasticsearch
      - kibana

  # golang-application:
  #   build:
  #     context: ./go-app
  #   ports:
  #     - 8080:8080
  #   container_name: golang-application
  #   command: go run github.com/StefanTruong/go-server
  #   volumes:
  #     - ./go-app:/app
  #   networks:
  #     - elk

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    networks:
      - elk
    depends_on:
      - elasticsearch
      - logstash
      - kibana

networks:
  elk:
    driver: bridge

volumes:
  elk_data:
  ls_data:
  kb_data: