filebeat.inputs:
  - type: container
    paths:
      - "/var/lib/docker/containers/*/*.log" # Путь к логам контейнеров Docker
    stream: all
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock" # Добавление метаданных Docker
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true

output.logstash:
  hosts: ["logstash:5044"] # Отправка логов в Logstash